from typing import Protocol, Tuple, Callable, Union, Any


class MapWidgetProtocol(Protocol):
    canvas: any
    width: int
    height: int
    lower_right_tile_pos: Tuple[float, float]
    upper_left_tile_pos: Tuple[float, float]
    move_velocity: Tuple[float, float]
    fading_possible: bool
    last_move_time: Union[float, None]
    zoom: float
    tile_size: int

    def convert_canvas_coords_to_decimal_coords(self, canvas_x: int, canvas_y: int) -> tuple: ...
    def check_map_border_crossing(self) -> None: ...
    def draw_rounded_corners(self) -> None: ...
    def draw_move(self) -> None: ...
    def set_zoom(self, zoom: float, relative_pointer_x: float = 0.5, relative_pointer_y: float = 0.5) -> None: ...
    def fading_move(self) -> None: ...
    def after(self, ms: int, func: Callable = None, *args: Any) -> str: ...
    def bind(self, sequence: str = None, func: Callable = None, add: str = None) -> str: ...
